<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXp4zw81\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXp4zw81/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXp4zw81.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXp4zw81\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXp4zw81\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xp4zw81',
    'container.build_id' => '5b3b1ba4',
    'container.build_time' => 1685208566,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXp4zw81');
